### PR TITLE
changed data structures

### PR DESCRIPTION
**Pull request by Siddhinita**
1. changed the <student ID, score> to <team, score>
2. added new test case in the form of csv files

### CODE REVIEW

**Comment by mukkachaitanya** [comment]
Hey @Siddhinita ! 
Can you just check why the test and checks are failing and rectify them accordingly?

**Comment by Siddhinita** [comment]
@mukkachaitanya the code climate review is an issue of code duplication.That's required for the code.So,I think that can be ignored. There are some formatting changes which I will take care of.
 The Travis CI has problems with the sql test files. Since I changed the input data structures,the sql test files are no longer valid.So do you want me to update them?

**Comment by mukkachaitanya** [comment]
@Siddhinita Yes. And I think it also in the best interests if you can lint and fix errors if an before pushing.
Use `./node_modules/.bin/eslint --fix .` in the root directory of the repo. Make sure you done `npm install` before it.

**Comment by mukkachaitanya** [comment]
Integrated in branch `data_structures` and will be merged

**Pull request closed without merging**
